Adding msg.port to input and some docs
MaddyTP/node-red-contrib-ezo pull request #6
Opened 2021-10-28 14:32 UTC by papakpmartin

I thought that maybe also adding `msg.port` could be useful for dynamic flows. For example, I have a case where I'm using a I2C port expander. However, note that I wasn't able to test this code as my current setup has my EZO devices on the normal `/dev/i2c-1` port.

2021-10-28 18:32 UTC, MaddyTP requested changes
Lets change this to `msg.bus` to follow common I2C terminology.  If we are to add a `msg.bus` property it makes sense to also include a field in the HTML file which allows the user to set their own default bus.  Something like this placed directly below the 'Topic' field:

```
<div class="form-row">
        <label for="node-input-bus"><i class="fa fa-address-card-o"></i> Bus</label>
        <input type="number" id="node-input-bus" style='width: 100px;' min=0 max=6>
</div>
```

Also, please remove your added linting so the PR is easier to review.  Most of the current format is to make viewing the code a little easier for other NR users.

2021-12-26 23:03 UTC, MaddyTP commented
Feature added in v1.4.0

2021-12-26 23:03 UTC, closed without merging

2022-01-03 17:37 UTC, papakpmartin commented
Thanks for adding this in, @MaddyTP! Sorry my default linting made things messy and that I wasn't able to get back to this.

2022-01-03 18:07 UTC, MaddyTP commented
No worries!  I had some time on my hands and needed to confirm the new HUM-C was supported at the same address as the existing humidity module.  Thought why not add this in for users while I'm at it.  :)